package message

const (
	ErrOpenConnDB       = "ERROR OPEN CONNECTION DB"
	ErrCloseConnDB      = "ERROR CLOSE CONNECTION DB FOR RETURNING TO POOL"
	ErrConnNilDB        = "ERROR CONNECTION DB IS NILL"
	ErrCloseQueryRowsDB = "ERROR CLOSE ROWS FOR FREE FOR DATA"
	ErrScanRowDB        = "ERROR SCAN ROW DATA"
	ErrScanRowsDB       = "ERROR SCAN ROWS DATA"
	ErrOpenStmtDB       = "ERROR START PREPARED STATEMENT"
	ErrCloseStmtDB      = "ERROR CLOSE PREPARED STATEMENT FOR FREE TO MEMORY"
	ErrQueryRowDB       = "ERROR QUERY ROW TO DATA"
	ErrQueryRowsDB      = "ERROR QUERY ROWS TO DATA"
	ErrExecDB           = "ERROR EXEC TO DATA"
	ErrOpenTxDB         = "ERROR START TRANSACTION"
	ErrTxNilDB          = "ERROR TRANSACTION IS NIL"
	ErrRollbackTxDB     = "ERROR ROLLBACK TRANSACTION"
	ErrCommitTxDB       = "ERROR COMMIT TRANSACTION"

	ErrEncodeJson = "JSON ENCODED ERROR"
	ErrParseForm  = "PARSE FORM ERROR"

	ErrOpenConnMinio = "ERROR OPEN CONNECTION MINIO"
	ErrPutMinio      = "ERROR MINIO PUT OBJECT"
	ErrDelMinio      = "ERROR MINIO REMOVE OBJECT"

	ErrOpenFile  = "ERROR CANNOT OPEN FILE HEADER"
	ErrCloseFile = "ERROR CANNOT CLOSE FILE HEADER"

	ErrInvalidEmail        = "INVALID EMAIL FORMAT"
	ErrInvalidTimeLayout   = "INVALID TIME LAYOUT"
	ErrInvalidIanaTimezone = "INVALID IANA TIMEZONE"
)
