name: account svc deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      dind:
        image: docker:23.0-rc-dind-rootless
        ports:
          - 2375:2375
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: set up go
        uses: actions/setup-go@v2
        with:
          go-version: "1.20"

      - name: run test
        run: make test